version: '3.8'

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: blog
      MYSQL_DATABASE: blog
      MYSQL_USER: blog
      MYSQL_PASSWORD: blog
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql

  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/blog
    depends_on:
      - database
    # Permet à docker de rediriger les requêtes vers les bons hosts à nginx
    external_links:
      - nginx:blog.fr.lan
      - nginx:www.blog.fr.lan

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/var/www/blog
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/ssl/certs
    depends_on:
      - php
      - database

  node:
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
      target: symfony_node
    volumes:
      - ./:/srv/app
    command: 'sh -c "yarn install; yarn run build; yarn run watch"'
